version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    container_name: postgres_test_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data:
